# Site settings
title: Of10 | Coworking Space | Event Space
email: mail@of10.in
url: https://of10.in
description: "6000 sq/ft shared office space in Hiranandani Gardens, Powai open to all entrepreneurs and startups. "

# Footer settings
footer: Of10

# Build settings
markdown: kramdown
permalink: pretty
