# Site settings
title: Coworking Space | Office Space | Events Space | Of10 Mumbai
url: https://of10.in/
description: "Of10 is an expertly designed 24x7 coworking community, meeting and event space, centrally located, in the best suburb of Powai, Mumbai.
Call 9920290368 to book."
keywords: "coworking spaces mumbai,co-working space mumbai,event space, desk space,
office space ,office on rent,business centre,powai,hiranandani,training,freelancer,
independent artist,entrepreneur,entrepreneurship,coder,programmer,hackathon,startup,
start-up,journalist,consultant,bombay,social media,social service,venture,angel,investor,
play,place,fun,study,learn,hangout,central,central mumbai,suburb,sme,techpreneur,tech,
shared office,edupreneur,studentpreneur,student,work from home,work from
ccd,cabins,meeting room,venue,event,Mumbai,coworking space"
# Footer settings
footer: Of10
author: Of10

authors:
  umang:
    display_name: Umang Sood
    email: umangsood@of10.in
    pic: umang.jpg
    web: http://www.umangsood.com/
    facebook: umangsood
    twitter: umangsood
  kaveri:
    display_name: Kaveri Tikmani
    email: kaveri@writesideup.com
    pic: kaveri.jpg
    web: http://www.writesideup.com/
    facebook: kaveri
    twitter: kaveritikmani
  upahar:
    display_name: Upahar Sood
    email: upaharsood@of10.in
    pic: upahar.jpg
    web: http://www.upaharsood.com/
    twitter: upaharsood
    facebook: upahar.sood
    github: usood
  team:
    display_name: Of10 Team
    email: work@of10.in
    pic: of10.png
    web: http://www.of10.in/
    twitter: workof10
    facebook: workof10

# Build settings
paginate: 2
paginate_path: "/blog/page:num/"
markdown: kramdown
permalink: pretty
